FROM scratch

LABEL org.opencontainers.image.title="Docker disk usage" \
    org.opencontainers.image.description="A sample extension to show how to run docker commands from Desktop Extensions." \
    org.opencontainers.image.vendor="Docker Inc." \
    com.docker.desktop.extension.api.version=">= 0.2.0"

COPY ui ./ui
COPY metadata.json .
