FROM scratch

LABEL org.opencontainers.image.title="SwimmingWhale" \
    org.opencontainers.image.description="A sample plugin that just displays a whale swimming." \
    org.opencontainers.image.vendor="Docker Inc." \
    com.docker.desktop.extension.api.version=">= 0.2.0"

COPY docker.svg .
COPY ui ./swim
COPY metadata.json .
