name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  directories:
    name: List child folders to build
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: echo "::set-output name=dir::$(ls -d samples/*/ | jq -R -s -c 'split("\n")[:-1]')"
  build:
    name: Build extensions
    runs-on: ubuntu-latest
    needs: [directories]
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}} # List matrix strategy from directories dynamically
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build sample ${{ matrix.dir }}
        run: cd ${{ matrix.dir }} ; make build-extension
        env:
          DOCKER_BUILDKIT: 1
