name: Build and Deploy to Netlify
on:
  release:
    types: [published] # a release, pre-release, or draft of a release is published

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "main"
      tag:
        description: "Release Tag"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docs
        uses: addnab/docker-run-action@v3
        with:
          image: squidfunk/mkdocs-material:latest
          options: -v ${{ github.workspace }}:/docs
          run: mkdocs build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./site"
          production-deploy: true
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions. Commit: ${{ github.sha }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DOCKER_EXTENSIONS_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DOCKER_EXTENSIONS_SITE_ID }}
        timeout-minutes: 3
